### ISSUE TITLE
http-text fails with "no matching clause"

### ISSUE THREAD

**Issue by jmglov** [mhuebert/maria#241]
### Issue:

Trying to load a Clojure file using `http-text` fails with an error.

For example, the browsing to https://www.maria.cloud/http-text/https:/raw.githubusercontent.com/clojure/clojurescript/master/src/main/clojure/cljs/support.cljc produces:
```
Error: No matching clause: ["http-text" "https:" "raw.githubusercontent.com" "clojure" "clojurescript" "master" "src" "main" "clojure" "cljs" "support.cljc"]
```

### Environment:

  - Browser: Firefox and Chrome
  - Platform (Mac/Windows/Linux): Linux
  
### URL to a gist replicating the issue (if possible/relevant)  

https://www.maria.cloud/http-text/https:/raw.githubusercontent.com/clojure/clojurescript/master/src/main/clojure/cljs/support.cljc

**Comment by mhuebert** [comment]
Hi Josh, thanks for the issue. Previously this required running a url through `js/encodeURIComponent` or the like but I've just pushed a fix which supports ordinary URLs like you've used.

I just made a whole bunch of small changes to Maria to get it running with the latest versions of ClojureScript / shadow-cljs (there were some bugs in cljs that prevented Maria from compiling awhile back, and that's what made this project more-or-less frozen for awhile), so I am only pushing this to dev.maria.cloud for now -- need to wait a bit to see how stable things are before we release to Maria.cloud.

fixed here: https://github.com/mhuebert/maria/commit/6793b6b50e446c7c2f4a99338cda91a85157890e

**Comment by jmglov** [comment]
Hi Matt, it doesn't quite seem to work, unless I'm doing something wrong.

If I browse to https://dev.maria.cloud/http-text/https:/raw.githubusercontent.com/clojure/clojurescript/master/src/main/clojure/cljs/support.cljc, this is what I see:

```html
<!DOCTYPE html>

<html><html lang="en"><head><meta content="width=device-width, initial-scale=1" name="viewport"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><title>Maria</title><link href="/trusted.css" rel="stylesheet"></head><body><div id="maria-index"></div><script src="/js/compiled/trusted/shadow-trusted.1EAF8FF3B25D0B985F847B7746DAA924.js"></script></body></html></html>
```

Maria does treat this as Clojure code, but of course you can't eval it.

Am I missing something?

**Comment by mhuebert** [comment]
Hi @jmglov, you're not missing something - something odd happens in prod that doesn't show up in dev with localhost instead of a real domain name. It seems to only occur when the leading `https://` is present in the url, so in 1558656 I've changed the API to support URLs containing just a domain name & path (without `https://`). 

Originally this endpoint expected only URLs that were encoded (eg. via `js/encodeURIComponent`) but I think it's worth supporting simple copy/paste here.

This works for me now: https://dev.maria.cloud/http-text/raw.githubusercontent.com/clojure/clojurescript/master/src/main/clojure/cljs/support.cljc

**Comment by jmglov** [comment]
OK, cool. It works on dev for me as well. I guess you just haven't deployed to prod yet? Prod's still broken for me: https://www.maria.cloud/http-text/raw.githubusercontent.com/clojure/clojurescript/master/src/main/clojure/cljs/support.cljc
